#!/bin/sh

# Set these paths appropriately

BIN="/Users/hamaike/src/words_for_developers/TreeTagger/bin"
CMD="/Users/hamaike/src/words_for_developers/TreeTagger/cmd"
LIB="/Users/hamaike/src/words_for_developers/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/danish-abbreviations
PARFILE=${LIB}/danish.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
