#!/bin/sh

# Set these paths appropriately

BIN="/Users/hamaike/src/words_for_developers/TreeTagger/bin"
CMD="/Users/hamaike/src/words_for_developers/TreeTagger/cmd"
LIB="/Users/hamaike/src/words_for_developers/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/romanian-abbreviations
PARFILE=${LIB}/romanian.par

$TOKENIZER -r -a $ABBR_LIST $* |
${CMD}/split-romanian.perl ${LIB}/romanian-tokens |
$TAGGER $OPTIONS $PARFILE
