#!/bin/sh

# Set these paths appropriately

BIN="/Users/hamaike/src/words_for_developers/TreeTagger/bin"
CMD="/Users/hamaike/src/words_for_developers/TreeTagger/cmd"
LIB="/Users/hamaike/src/words_for_developers/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
