#!/bin/sh

# Set these paths appropriately

BIN="/Users/hamaike/src/words_for_developers/TreeTagger/bin"
CMD="/Users/hamaike/src/words_for_developers/TreeTagger/cmd"
LIB="/Users/hamaike/src/words_for_developers/TreeTagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
